# Project information
site_name: DVC-NLP-project-with-docs
# defeine TOC or order of website-
nav:
  - Home: index.md

site_author: Rajesh Kumar Thakur
site_description: >-
  DESCRIPTION

# Repository
repo_name: RajeshThakur1/DVC-NLP-project-with-docs
repo_url: https://github.com/RajeshThakur1/DVC-NLP-project-with-docs

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime    
  # logo: PyTorch_logo_icon.svg
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/RajeshThakur1
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/c17hawke
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rajesh-thakur-b87b26151/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/rajeshthakur3014/

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
  
plugins:
  - search

copyright: |
  &copy; 2022 <a href="https://github.com/RajeshThakur1"  target="_blank" rel="noopener">Rajesh Thakur</a>